tesseract_mooc_log:
    resource: "@TesseractMOOCBundle/Resources/config/routing/log.yml"
    prefix:   /log

tesseract_mooc_homepage:
    path:     /
    defaults: { _controller: TesseractMOOCBundle:Organisation:inscriptionOrganisation }
    
tesseract_mooc_apprenant_interface:
    path:     /apprenant
    defaults: { _controller: TesseractMOOCBundle:Apprenant:index }

tesseract_mooc_admin_dashboard:
    path:     /admin
    defaults: { _controller: TesseractMOOCBundle:Admin:index }

tesseract_mooc_admin_tickets:
    path:     /admin/tickets
    defaults: { _controller: TesseractMOOCBundle:Tickets:index }

tesseract_mooc_admin_tickets_reply:
    path:     /admin/tickets/{id}
    defaults: { _controller: TesseractMOOCBundle:TicketReply:index }
    
tesseract_mooc_admin_tickets_sendMail:
    path:     /admin/tickets/sendMail/{mail}
    defaults: { _controller: TesseractMOOCBundle:TicketReplySent:index }

tesseract_mooc_admin_org_qry:
    path:     /admin/orgquery
    defaults: { _controller: TesseractMOOCBundle:OrganisationQueries:index }

tesseract_mooc_admin_org_qry_reply:
    path:     /admin/orgquery/{reply}/{id}
    defaults: { _controller: TesseractMOOCBundle:OrganisationQueries:reply }

tesseract_mooc_admin_block_users:
    path:     /admin/blockusers
    defaults: { _controller: TesseractMOOCBundle:BlockUsers:index }

tesseract_mooc_admin_block_user:
    path:     /admin/block/{id}
    defaults: { _controller: TesseractMOOCBundle:BlockUsers:block }

tesseract_mooc_admin_social_media:
    path:     /admin/social
    defaults: { _controller: TesseractMOOCBundle:SocialMedia:index }
    
tesseract_mooc_admin_forum_bans:
    path:     /admin/forumbans
    defaults: { _controller: TesseractMOOCBundle:ForumBans:index }

tesseract_mooc_admin_chart:
    path:     /admin/chart
    defaults: { _controller: TesseractMOOCBundle:Graphe:index }
tesseract_mooc_admin_user_list:
    path:     /admin/userlist
    defaults: { _controller: TesseractMOOCBundle:Utilisateur:list }
    
tesseract_mooc_oranisation_register_interface:
    path:     /registerorg
    defaults: { _controller: TesseractMOOCBundle:Organisation:inscriptionOrganisation }

tesseract_profile_apprenant:
    path:    /profileapprenant
    defaults: { _controller: TesseractMOOCBundle:Apprenant:profileApprenant }
    
tesseract_afficher_cours_categ:
    path:    /courses-categ
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesCategApprenant }
    
course_subscribed_id:
    path:   /course-subed
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesSubedApprenant }
    
course_comments_id:
    path:   /course-comm
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesCommentsApprenant }
    
afficher_cours_chap_appr:
    path:     /session
    defaults: { _controller: TesseractMOOCBundle:Apprenant:afficherContenuCours }
terminer_cours_chap_appr:
    path:     /nextsession
    defaults: { _controller: TesseractMOOCBundle:Apprenant:terminerCours }
tesseract_mooc_organisation_home:
    path:     /orgHome
    defaults: { _controller: TesseractMOOCBundle:Organisation:index}
    
organisation_show:
    path:     /1/{id}
    defaults: { _controller: TesseractMOOCBundle:Organisation:show}
    
organisation_edit:
    path:     /2/{id}
    defaults: { _controller: TesseractMOOCBundle:Organisation:edit}
    
organisation_delete:
    path:     /3/{id}
    defaults: { _controller: TesseractMOOCBundle:Organisation:delete}
    
organisation_new:
    path:     /4
    defaults: { _controller: TesseractMOOCBundle:Organisation:new}
tesseract_mooc_Org_coach_req:
     path:     /Org_coach_req
     defaults: { _controller: TesseractMOOCBundle:Organisation:respond}
tesseract_mooc_org_accept:
     path:     /accept/{id}
     defaults: { _controller: TesseractMOOCBundle:Organisation:accept}

tesseract_mooc_org_refuse:
     path:     /refuse/{id}
     defaults: { _controller: TesseractMOOCBundle:Organisation:refuse}
tesseract_mooc_Org_affiliate:
     path:     /affiliate
     defaults: { _controller: TesseractMOOCBundle:Organisation:affiliate}

    
   