tesseract_mooc_homepage:
    path:     /
    defaults: { _controller: TesseractMOOCBundle:Organisation:inscriptionOrganisation }
tesseract_mooc_homepage_2:
    path:     /home
    defaults: { _controller: TesseractMOOCBundle:Default:index }
tesseract_mooc_apprenant_interface:
    path:     /apprenant
    defaults: { _controller: TesseractMOOCBundle:Apprenant:index }

tesseract_mooc_admin_dashboard:
    path:     /admin
    defaults: { _controller: TesseractMOOCBundle:Admin:index }

tesseract_mooc_oranisation_register_interface:
    path:     /registerorg
    defaults: { _controller: TesseractMOOCBundle:Organisation:inscriptionOrganisation }


tesseract_profile_apprenant:
    path:    /profileapprenant
    defaults: { _controller: TesseractMOOCBundle:Apprenant:profileApprenant }
    
tesseract_afficher_cours_categ:
    path:    /courses-categ
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesCategApprenant }
    
course_subscribed_id:
    path:   /course-subed
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesSubedApprenant }
    
course_comments_id:
    path:   /course-comm
    defaults: { _controller: TesseractMOOCBundle:Apprenant:coursesCommentsApprenant }
    
afficher_cours_chap_appr:
    path:     /session
    defaults: { _controller: TesseractMOOCBundle:Apprenant:afficherContenuCours }
terminer_cours_chap_appr:
    path:     /nextsession
    defaults: { _controller: TesseractMOOCBundle:Apprenant:terminerCours }
   