tesseract_mooc_homepage:
    path:     /
    defaults: { _controller: TesseractMOOCBundle:Default:index }
tesseract_mooc_apprenant_interface:
    path:     /apprenant
    defaults: { _controller: TesseractMOOCBundle:Apprenant:index }