services:
    app.form.registration:
        class: Tesseract\MOOCBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    redirect.after.login:
        class: Tesseract\MOOCBundle\Redirection\AfterLoginRedirection
        arguments: [@router]
