tesseract_mooc:
    resource: "@TesseractMOOCBundle/Resources/config/routing.yml"
    prefix:   /tesseract

app:
    resource: @AppBundle/Controller/
    type:     annotation


fos_user:
    prefix:   /tesseract
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /tesseract_messages