<?php

namespace Proxies\__CG__\Tesseract\MOOCBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \Tesseract\MOOCBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'nom', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'difficulte', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'badge', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'affiche', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'video', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'validation1', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'validation2', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'language', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'upload', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'idUtilisateur', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'idMatiere'];
        }

        return ['__isInitialized__', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'nom', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'difficulte', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'badge', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'affiche', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'video', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'validation1', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'validation2', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'language', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'upload', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'idUtilisateur', '' . "\0" . 'Tesseract\\MOOCBundle\\Entity\\Cours' . "\0" . 'idMatiere'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDifficulte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDifficulte', []);

        return parent::getDifficulte();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getBadge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBadge', []);

        return parent::getBadge();
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiche', []);

        return parent::getAffiche();
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidation1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidation1', []);

        return parent::getValidation1();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidation2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidation2', []);

        return parent::getValidation2();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpload', []);

        return parent::getUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUtilisateur', []);

        return parent::getIdUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMatiere', []);

        return parent::getIdMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function setDifficulte($difficulte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDifficulte', [$difficulte]);

        return parent::setDifficulte($difficulte);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setBadge($badge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBadge', [$badge]);

        return parent::setBadge($badge);
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiche($affiche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiche', [$affiche]);

        return parent::setAffiche($affiche);
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function setValidation1($validation1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidation1', [$validation1]);

        return parent::setValidation1($validation1);
    }

    /**
     * {@inheritDoc}
     */
    public function setValidation2($validation2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidation2', [$validation2]);

        return parent::setValidation2($validation2);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpload(\DateTime $upload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpload', [$upload]);

        return parent::setUpload($upload);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUtilisateur(\Tesseract\MOOCBundle\Entity\Utilisateur $idUtilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUtilisateur', [$idUtilisateur]);

        return parent::setIdUtilisateur($idUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMatiere(\Tesseract\MOOCBundle\Entity\Matiere $idMatiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMatiere', [$idMatiere]);

        return parent::setIdMatiere($idMatiere);
    }

}
